package application;

import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.Tab;
import javafx.scene.control.TextField;

public class RssFeedController implements Initializable {
	
	@FXML
	private Tab					newsTab;
	@FXML
	private ListView<String>	newsList;
	@FXML
	private Tab					settingsTab;
	@FXML
	private ListView<String>	urlList;
	@FXML
	private TextField			rssUrlTextField;
	@FXML
	private Button				addButton;
	@FXML
	private Button				editButton;
	@FXML
	private Button				removeButton;
	
	public RssFeedController() {
		// TODO Auto-generated constructor stub
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see javafx.fxml.Initializable#initialize(java.net.URL, java.util.ResourceBundle)
	 */
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		System.out.println("initialize");
		
		Platform.runLater(() -> {
			// FIXME get the news list from settings and populate with the news
			// for start, get only the last X news,
			// later, save the last new from each channel, and download just the news past that last one
			
			
			ObservableList<String> newsSources = urlList.getItems();
			
			
			for (String url: newsSources) {
				//FIXME
				//here get the news;
				
				
				
			}
			
			
		});
		
	}
	
	// Event Listener on Button[#addButton].onAction
	@FXML
	public void onActionAddButton(ActionEvent event) {
		// TODO Autogenerated
		ObservableList<String> items = urlList.getItems();
		items.add(0, rssUrlTextField.getText());
		urlList.setItems(items);
	}
	
	// Event Listener on Button[#editButton].onAction
	@FXML
	public void onActionEditButton(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#removeButton].onAction
	@FXML
	public void onActionRemoveButton(ActionEvent event) {
		// TODO Autogenerated
		int indexOfSelectedItem = urlList.getSelectionModel().getSelectedIndex();
		
	}

	@FXML public void onMouseClickedNewsList() {
		//get the selected item
		//parse with a DOM and extract the page body/the news article
		
		
		//put the info in another tab for now
		
		//switch to that tab
		//or put a back button
		
		//once you left the extended news tab, kill the tab to release the resources
	}
}
